version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  web:
    build: ./app
    container_name: php-app
    volumes:
      - ./app/src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
 
